apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eksreadonly-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - events
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eksreadonly-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: eksreadonly-clusterrole
  apiGroup: rbac.authorization.k8s.io  
subjects:
- kind: Group
  name: eks-readonly-group
  apiGroup: rbac.authorization.k8s.io

