apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels: 
    app: backend-restapp
    tier: backend
spec:
  selector:
    app: backend-restapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
